'''
assignment:Data Handling with pandas and Numpy


sectionI

1.installation of pandas library:
   command to install pandas lib: pip install pandas
   use of pandas is to arrange the data in an organised manner
   here we mostly arrange the data in rows and coloumns with the help of pandas

2.import of pandas:
    command to import pandas is: import pandas as pd(here the variable can be anything)
    it is important to install a library before using it because for every type of fuction 
    the programmer has designed some set of predefined instructions to develop a project but due to the restrictions in data management they cannot be stored into a sigle file or folder,as we are extracting files from outer source we have to save the data on to our current directory to make the execution process simple.

'''

In [1]:
#3.dataframe creation using given information:   
#to create a data frame write the code as below
import numpy as np
import pandas as pd
df = pd.DataFrame({'Name': ['John', 'Alice', 'Bob'], 'Age': [25, 30, 22], 'Score': [85, 90, 88]})
df


Name  Age  Score
0   John   25     85
1  Alice   30     90
2    Bob   22     88

In [2]:
df.tail(2)

Name  Age  Score
1  Alice   30     90
2    Bob   22     88

In [3]:
df.head(2)

Name  Age  Score
0   John   25     85
1  Alice   30     90

In [4]:
#4.DataFrame and Series  
'''

difference between dataframe and series:
dataframe is mostly record the data as rows and columns whereas the series is the collection of data in particular coloumn
'''
ss=df.iloc[:,1:2]
ss

Age
0   25
1   30
2   22

In [5]:
#5.Handling Missing Values 

rr = pd.DataFrame({'Name': ['John', 'Alice', np.nan], 'Age': [np.nan, 30, np.nan], 'Score': [np.nan, 90, 88]})
rr.isnull()



Name    Age  Score
0  False   True   True
1  False  False  False
2   True   True  False

In [6]:
rr.isnull().sum()

Name     1
Age      2
Score    1
dtype: int64

In [7]:
#6.Dictionary with DataFrame  
data = {'A': [1, 2, 3], 'B': [1, 1, 1]}
cc=pd.DataFrame(data)
cc


A  B
0  1  1
1  2  1
2  3  1

In [8]:
#7.CSV Operations
#converting dataframe into a csv file
cc.to_csv("faltoo.csv",index=True)  

In [9]:
#readind a saved csv file
dataframe=pd.read_csv(r"D:\datascience\faltoo.csv")
print(dataframe,"\n")

   Unnamed: 0  A  B
0           0  1  1
1           1  2  1
2           2  3  1 



In [10]:
'''


Section 2: Numpy Basics

1.Installation and Import of Numpy 
    command to istall and import numpy library:
    a)pip install numpy 
    b)import numpy as np    
'''

'\n\n\nSection 2: Numpy Basics\n\n1.Installation and Import of Numpy \n    command to istall and import numpy library:\n    a)pip install numpy \n    b)import numpy as np    \n'

In [11]:
#2. Array Creation and Manipulation 
arr=np.arange(0,20)
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
arr.shape

(20,)

In [13]:
#3. 2D and 3D Arrays 
sd=np.array([0,0,0,0,0,0,0,0,0])
mm=sd.reshape(3,3)

In [14]:
#3D arrays
B=np.array([[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]])
print(B.shape)
mm.shape

(2, 3, 3)


(3, 3)

In [15]:
#4. Identity Matrix  
cc=np.eye(3,3)
cc
#identity matrix is a matrix with diagonal elements as "1"


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#5. Mathematical Operations 
#addition
a=np.arange(0,6)
aa=a.reshape(3,2) 
b=np.arange(6,12)
bb=a.reshape(3,2)
vv=aa+bb
vv

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [17]:
#subtraction
x=aa-bb
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [18]:
y=aa*bb
y

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [19]:
k=np.arange(0,9)
kk=k.reshape(3,3)
j=np.arange(12,21)
jj=j.reshape(3,3)
ii=jj*kk
ii

array([[  0,  13,  28],
       [ 45,  64,  85],
       [108, 133, 160]])

In [24]:

#Section 3: DataFrame Advanced Operations
#1. Accessing Data in DataFrames 
df=pd.DataFrame(data=jj,columns=["product","price","stock"])
df

product  price  stock
0       12     13     14
1       15     16     17
2       18     19     20

In [25]:
#accessing first three 3 rows
f=np.arange(0,25)
ff=f.reshape(5,5)
ef=pd.DataFrame(data=ff,index=["row1","row2","row3","row4","row5"],columns=["product","price","stock","age","happy"])
ef.iloc[:3,:]
ef

product  price  stock  age  happy
row1        0      1      2    3      4
row2        5      6      7    8      9
row3       10     11     12   13     14
row4       15     16     17   18     19
row5       20     21     22   23     24

In [26]:
#accessing specific column price
cf=df.iloc[:,1:2]
cf

price
0     13
1     16
2     19

In [28]:
#extracting the value in 2row and 2column
rf=df.iloc[1:2,1:2]
rf

price
1     16

In [30]:
#2. Renaming Columns
sf=df.rename(columns={'price':'cost'})  
sf

product  cost  stock
0       12    13     14
1       15    16     17
2       18    19     20

In [34]:
#3. Handling Missing Data 
q=[[1,np.nan,np.nan],[3,np.nan,5],[3,4,np.nan]]
qq=pd.DataFrame(data=q,index=["row1","row2","row3"],columns=["col1","product","col3"])
qq.isnull()

col1  product   col3
row1  False     True   True
row2  False     True  False
row3  False    False   True

In [35]:
qq.isnull().sum()

col1       0
product    2
col3       2
dtype: int64

In [43]:
#4. Value Counts and Unique Values 
z={
    "names":["rani","raju","ravi","rinki"],
    "place":["hyd","nzb",'kmr','rrk'],
    "product":["tv",'laptop','iphone','tab'],
    "cost":[12,13,134,78]
}
zz=pd.DataFrame(data=z,index=["a",'b','c','d'],columns=['names','place','product','cost'])
zz

names place product  cost
a   rani   hyd      tv    12
b   raju   nzb  laptop    13
c   ravi   kmr  iphone   134
d  rinki   rrk     tab    78

In [45]:
pd.unique(z['product'])

array(['tv', 'laptop', 'iphone', 'tab'], dtype=object)

In [46]:
pd.value_counts(z['cost'])

12     1
13     1
134    1
78     1
dtype: int64

In [51]:
#5. Exporting to CSV with index
zz.to_csv('faltoo.csv',index=True)
h=pd.read_csv('faltoo.csv')
print(h,"\n")

  Unnamed: 0  names place product  cost
0          a   rani   hyd      tv    12
1          b   raju   nzb  laptop    13
2          c   ravi   kmr  iphone   134
3          d  rinki   rrk     tab    78 



In [52]:
##5. Exporting to CSV without index
zz.to_csv('faltoo.csv',index=False)
h=pd.read_csv('faltoo.csv')
print(h,"\n")

   names place product  cost
0   rani   hyd      tv    12
1   raju   nzb  laptop    13
2   ravi   kmr  iphone   134
3  rinki   rrk     tab    78 



In [53]:
#Bonus Section: Problem Solving

#creating 5x5 identity matrix(using numpy)
u=np.eye(5)
u




array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
p=2
pr=u*p
pr

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [58]:
st=np.arange(0,4)
stt=st.reshape(2,2)
ts=pd.DataFrame(data=stt,index=["A",'B'],columns=['col1','col2'])
ts

col1  col2
A     0     1
B     2     3